### ISSUE TITLE
Script has to load the database file, and build the annoy index on every exhchange.

### ISSUE THREAD

**Issue by Dalhimar** [YenRaven/annoy_ltm#3]
According to the debug/logger, the script reloads the database/metadata file, and rebuilds the annoy index for every exchange with the AI that is made.
`loaded metadata file (221)`
`hashes check passed, proceeding to load existing memory db...`
`loaded 220 items from existing memory db`
`found 2 rows of chat history to be added to memory db. adding items...`
`building annoy index took 0.4716670513153076 seconds...`
Potential changes:
**1:** Load the database and metadata as global variables so that the script doesn't have to load the file on every exchange with the LLM.
**2:** Have the code run a comparison check on the data in RAM and the saved files, update save files as needed
**3:** Use the `threading` module to run the comparison check and save functions in the background while the rest of the program proceeds
**4:** Currently the program is only persistent if the user does not clear the history of the conversation, unless I missed something. It would be a good idea to save a copy of the chat, allowing it to persist even if the chat is cleared. This could be made optional by providing a button on the oobabooga interface that would let the user delete the chat log saved by annoy_ltm.

In regards to the annoy index. I know nothing about how annoy works at the moment, so these are more of thoughts on it.
**1:** If possible, keep the index in memory
**2:** Instead of rebuilding it every time in sequence with the main code, possibly offload the rebuild to another thread while using the index that was most recently completed. This might make the index lag behind by 1, maybe 2 exchanges with the LLM if you're going about it rapid fire, but as long as the last couple of exchanges fit inside the token limits, I don't see this as much of an issue unless the index is required to be updated for the memory retrieval.

Edit:
I just noticed that the index also rebuilds if you use the regenerate function in chat mode, most likely due to the failed hash check. Also... small typo in the message
`loaded metadata file (239)`
`hashes check failed, either an existing message changed unexpectdly or the extension code has changed. Rebuilding annoy db...`
`found 239 rows of chat history to be added to memory db. adding items...`
`building annoy index took 8.736616849899292 seconds...`

Another idea that might work for this, though I don't know how complex it would be to do, or even possible, If you can separate the index into 2 different ones.
A Primary index that is only updated with what could be considered old messages. This could be updated by a background thread.
A secondary, index that is used for the front facing activities and consist of say the last 10 exchanges, so if a rebuild is needed, it doesn't trigger the rebuild on all the data.

**Comment by YenRaven** [comment]
What kind of times are you seeing for index builds? Even with >1000 items in chat history, I'm seeing sub second builds on windows. I should clarify that I mean when adding the 2 new rows of the latest interaction and rebuilding the index. My build timer in my code tracks the entire process of checking the hash, grabbing embeddings for all the items needed to add to the db, adding those to the annoy index in memory and building/saving that file and the updated metadata file.  So if you do a "regenerate" command, it can take significantly longer as the bulk of the time seems to be from generating the embeddings for each chat message.

**Comment by Dalhimar** [comment]
The times I'm checking are for when a total rebuild is triggered. If I'm not regenerating the messages I do see times in the 200ms range. However there might be a way to increase the the efficiency of the process in cases where there is more than 1 embedding that needs to be done.
I was just looking at a level 5 log and your code. Correct me if I'm wrong, but the generate embeddings code currently works with 4 keywords at a time, generates the indicies and distances, then stores them. If I'm right, you could use multiple threads during the procedure. I.E. thread one works on keywords 1, 2, 3, 4. Thread 2, works on 4, 5, 6, 7. Both threads then jump forwards in the order by 3, so thread 1 works on 7, 8, 9, 10, thread 2 works on 10, 11, 12, 13. You could make this dynamic to the number of threads available on the machine so that it can scale up indefinitely.
I haven't had time to really sift through the embeddings code and understand it yet, though I have a basic framework that should allow it to be dynamically multi-threaded. If you think it might work, you'll probably be able to get it implemented faster than I can. Here is the framework [https://github.com/Dalhimar/multiprocess_frame](url)

**Comment by YenRaven** [comment]
Hey, that is awesome!  I see what you mean now about the keyword walking and multi-threading that! Excellent idea!

**Comment by Dalhimar** [comment]
So I don't think I will be able to get the multiprocessing to work the way I wanted, I will upload what I have been able to get working for that so others to take a look at it. 
I'm trying a different approach right now. Sorting and grouping the keywords isn't the slow part of the process as far as I can tell, it's the repeated calls and initialization of the tokenizer and/or torch.no_grad, so I'm attempting to change that to a batch operation.

**Comment by Dalhimar** [comment]
Well YenRaven, I'll admit I've hit the limit of what I know how to do right now. I don't know if it will be of any use to you, but I have it uploaded to my fork if you want to take a look.
I have the batch processing working, to a degree. When working with the keyword groups it processes them fine as far as I can tell, then adds them to the index. The issue I'm running into is that when the trimmed message is put through the code it generates the wrong size vector. When it is run through the original generate_embeddings code, it causes errors in the history lookup.
It also appears to be overall slower when rebuilding the database, though I don't know if that is because of my mediocre programming skills or something else.

**Comment by YenRaven** [comment]
Hey, no problem.  I'm not a great python developer either, just trying to muddle through. I'll take a look and see if between me and GPT-4 we can get it working! Thanks!

**Comment by YenRaven** [comment]
@Dalhimar I think I got something working in the code base after a lot of tinkering. I was able to use `concurrent.futures` to batch the database builds in a separate process and then when a prompt generation request comes in, it grabs the latest built database to use as the most current memory database. Check it out and let me know if this was along the lines you were hoping for?

**Comment by Dalhimar** [comment]
Just downloaded the batch database build branch to test. I turned the logger level up to 10 to make sure I'm seeing everything that happens. It appears that when it has to rebuild the database, it looses the ability to inject the memories into the prompt.
I tested it with a relatively short chat history and context length, less than 2000 token history with a context of 500 just to keep it quick. I load Ooba, the model, parameters and character, and start chatting. The database gets built on the first run, but does not appear to add the memories to the prompt. I reboot Ooba and reload everything, and then it appears to add the memories just fine. If do something that causes a database rebuild, the terminal no longer shows text between "Memories: " and "Chat: "
Before rebuild:
```
Gavin Breaker is a grizzled old bar keep in a fantasy dungeons and dragons setting. Gavin tends the bar and interacts with the guest. Gavin is sarcastic and sassy.

Memories:
Janice Just some porridge if you could
Gavin BreakerNo problem at all. One bowl of porridge coming right up. And while you wait why don't you take a look around. Our prices are quite reasonable and we offer discounts to regular customers.
Janice *I go an take a seat next to the large fireplace, waiting for my food and drink. I'm the only patron in the bar right now
Gavin BreakerHere you go. A nice hot bowl of porridge just how you like it. Enjoy! If you need anything else let us know. We're always happy to help.

Chat:
Janice Phew, doesn't seem like a great place to put a town with all that around

```


After rebuild:
```
Gavin Breaker is a grizzled old bar keep in a fantasy dungeons and dragons setting. Gavin tends the bar and interacts with the guest. Gavin is sarcastic and sassy.

Memories:

Chat:
Janice Phew, doesn't seem like a great place to put a town with all that around

```
Been working long hours lately and my brain is about fried, otherwise I'd try to trace the issue more. Attached is the terminal output I had, there are only about 5 exchanges made, just search for the following to jump to the end of each
`--------------------`
[Annoy batch branch log.txt](https://github.com/YenRaven/annoy_ltm/files/11714379/Annoy.batch.branch.log.txt)

**Comment by YenRaven** [comment]
Ah shoot, yeah, I have a few bugs to work out it looks like. That one is just the unload call on the annoy db in the script.py file. But there's another issue blocking the annoy db from saving to the hard drive. Looking into that now.

**Comment by YenRaven** [comment]
@Dalhimar That should fix the issue with the memories not properly being added.

**Comment by Dalhimar** [comment]
I finally had some time to come back to the division by 0 error. Added a check in my fork of the batch-database-builds to prevent the issue. Seems to be stable now, haven't had any more issues pop up. I'm going to start looking into how the concurrent.futures has effected things.

**Comment by YenRaven** [comment]
I've been using it for a while, I don't think concurrent.futures works the way I expect. The database build still seem very much synchronous with the other code. Not sure what I did wrong.

**Comment by YenRaven** [comment]
It looks like my refactor into the many other files caused some issues as well I've slowly been working through. I'll create a commit for my current set of fixes and push them to the branch later today. Should prevent a few other issues for you while you check it out.

**Comment by YenRaven** [comment]
Hey! It's working now! I've also included a change to get the new 8k superhot models working!
